AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config.ru'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 300

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Max: 30